### ISSUE TITLE
Not an Issue but a thankyou

### ISSUE THREAD

**Issue by liam-veitch** [consp/apim-asbuilt-decode#1]
Hi, many thanks for developing this program. I've used it recently to install a Gen4 APIM into a 2015 Focus and it was very easy to use.

I'm also a Python developer; and programmer in general of a couple of decades. If there's anything I can help with, please let me know.

**Comment by consp** [comment]
Thank you, you are free to submit pull requests. I'll review them and add them though I have no plans on extending it any further at this moment.

**Comment by consp** [comment]
I'll close the issue (Keep getting reports from github that one is open). Thaks anyway!
