### ISSUE TITLE
Not an issue - Collaboration

### ISSUE THREAD

**Issue by fma965** [consp/apim-asbuilt-decode#2]
Hi Mate, 

Amazing work you have done here, I am currently working on adding a bunch of new functionality to Syn3 Updater and wondered what would be the chances on working together or making this a web based project? 

Currently I am reading the log xml files generated by the ford logging utility and then parsing the asbuilt out of it in to a UCDS style format, if this was web based we could directly hook this in to it and collect and share asbuilt information very easily.
https://cyanlabs.net/applications/syn3-updater/

Happy to host it but i have no experience in Python

If you want to discuss further hit me up on my discord server https://discord.com/invite/GhmTgfV and be sure to join as a beta-tester to see the current status

**Comment by fma965** [comment]
My friend has already implemented a web UI for this so this can be closed.

**Comment by consp** [comment]
I'm not enough logged on github to see these requests straight away . Good to see you got your stuff working and closed it yourself.  Many Dutch people use it already (and sometimes require some help when something goes wrong), keep up the good work.
