### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by kdschlosser** [consp/apim-asbuilt-decode#3]
First off, great work on his project. It makes it a whole lot easier to alter the as built data.

One suggestion. Adding tool tips. I am a car guy and there are acronyms being used that I have never heard of. as an example "DM6 HMI". I do know what HMI (Human Machine Interface) is I don't know what DM6 is.

While using acronyms can be a fantastic way way of conveying information they can also be a problem. There can be the same acronym used between different platforms that mean something completely different.

Or you have differences like HMI for instance. Ford has HMI being "Human Machine Interaction" and the standard is "Human Machine Interface" which have 2 completely different meanings.

Now set aside the use of acronyms. Here is an example "Mode Man Icon (climate)" I think it has something to do with the climate controls and something to do with an icon and that is about it.

Providing some clarity as to what the items are or what they do would be really helpful.

You have a setting "Radio Tuner Market" which I believe should be "Radio Data System (RDS)" and it should have 2 options. "On" and "Off". There are radio stations in the US that do broadcast RDS information yet there is no listing for USA. There is a US variant of RDS called RBDS and RBDS is designed so it will work on RDS compatible radios. The two standards (RDS and RBDS) are more or less the same. The main difference is in the classification of the program type that is transmitted, such as news, sports, drama, pop music and jazz music.

The use of Radio Tuner Market would make me believe that  this would change the frequency range that is used in different regions of the world. Most regions of the world use 87.5–108 MHz range. there are a few exceptions. Japan uses 76–90 MHz and portions of Russia use 65.8–74 MHz which is slowly being phased out. 

If the Radio Tuner Market setting is specifically for RDS then there should only be 2 options. On and Off. and the label for the setting should be hanged to "Radio Data System (RDS/RBDS)". Maybe the setting is for defining the frequency range the radio should be using. I do not know as I have not tinkered with the setting. If it is for changing the frequency range of the radio then the label should reflect that "Radio Tuner Frequency Range (market)" with selections of "87.5–108 MHz (Global)", "76–90 MHz (Japan)" and "65.8–74 MHz (Russia)" 

another suggestion would be offering an alternate view that groups settings together by interface instead of by module number.

Radio settings would be grouped together. climate control settings would be grouped together and so on and so forth. There are people that are looking to expand the  functionality of what is see in the IP. There is a pretty universal misunderstanding of what the user seen portion of the HMI is. What the world has come to know as the "Radio" has changed into a combination of the  once know radio display and the instrument panel (IPC/gauge cluster/"gauges"). examples of this are "Heated seats HMI" and "PDC HMI" in which the first one gets displayed on the radio display and the latter gets displayed on the IPC. That's if the PDC is what I think it is, Parking sensors aka Park Distance Control

I think that letting the user know where something may be displayed would be a good idea. Or perhaps also offering alternate way to view settings for IPC display settings and also radio display settings.

tool tips are a great way to provide more information to the user without making the interface all cluttered.

**Comment by consp** [comment]
I like the suggestions but it's a hobby project and adding tooltips is quite some effort, maybe I'll do it in the future when I update it but don't count on it any time soon. Most of the data is collected from the devices themselves and for some stuff (like the DM6) device I also have no idea what it is. Most data is extracted verbatim from the debug information present in the code of the programs on the Sync module.

> There are radio stations in the US that do broadcast RDS information yet there is no listing for USA

True, but the settings are world wide, if there is no specific setting it most likely does nothing for US radios (there are minor differences in the radio tuners).

> The use of Radio Tuner Market would make me believe that this would change the frequency range that is used in different regions of the world. Most regions of the world use 87.5–108 MHz range. there are a few exceptions. Japan uses 76–90 MHz and portions of Russia use 65.8–74 MHz which is slowly being phased out.

These dictated by the radio unit as far as I know, not the APIM (Sync unit). I haven't looked into it enough to be sure thougn.

> another suggestion would be offering an alternate view that groups settings together by interface instead of by module number.

If anyone is willing to do that I'm fine with including the code, but it would require a major redesign of the tool. The tool is built around extracting data from the device and most settings are generated by a script which pulls the data from the programs which are installed on the device (which for legal reasons I will not include beyond what is already in the repository). Changing this requires quite some rework and moves away from the mostly automated extraction to all manual editing.

The tool is more or less meant for advanced users who know what the codes mean. Making it more common user friendly is always possible but not really my goal. For a maybe more user friendly experience you might want to take a look at the cyanlabs site (https://cyanlabs.net/fhub/asbuilt-db/) the creator of that site used some of the data in this app as far as I know and extended it a bit. Maybe it is more useful for you.

**Comment by kdschlosser** [comment]
So you are basically where I m and guessing at what some of the things actually do. I am not a novice with vehicles and they data systems and also not a novice with programming either. I would add the tool tips but I am not familiar with the QT framework. I am familiar with WX Widgets.

I may have a look at it and see if I am able to make alternate views and get some tool tips going.

**Comment by BillyCroan** [comment]
Where can we go to learn more about what the various asbuilt settings mean "Sound Immersion" for instance.  I'm looking for a paragraph that explains what that feature does.  What kind of sound?  immersed how?

**Comment by kdschlosser** [comment]
sound immersion is DSP.

**Comment by consp** [comment]
While these are nice idea's, the effort required will be a bit beyond my willingness to spend time on it. I'm going to close this issue for now.

As for the naming of things: Please call ford about it and make a issue when you get a response. The names are thought up by either their marketing department or the engineers designing it, I'm unfortunately not all knowing about this.

**Comment by kdschlosser** [comment]
I feel ya on it. Would you accept a pull request if I made the changes??

**Comment by consp** [comment]
Sure, though It's spaghettycode everyhere so be ware of all the mess.  Though the qt parts are a bit nicer than the parsing.
