### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by chaosben** [consp/apim-asbuilt-decode#4]
```
python3 apim.py ~/Downloads/WF0AXXWPMAFY66059.ab 
Loading /home/benjamin/Downloads/WF0AXXWPMAFY66059.ab
Loading Ford XML file
19
119f89c00340000004474d0000000000000000
0
Traceback (most recent call last):
  File "/home/benjamin/bin/apim-asbuilt-decode/src/asbuilt.py", line 92, in decode_bytes
    data = data[self.fieldsizes[i]:]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/benjamin/bin/apim-asbuilt-decode/src/apim.py", line 318, in <module>
    asbuilt1 = AsBuilt(abtfile[0]) if len(abtfile) > 0 else None
  File "/home/benjamin/bin/apim-asbuilt-decode/src/asbuilt.py", line 72, in __init__
    self.decode_bytes(unhexlify(bits.encode()))
  File "/home/benjamin/bin/apim-asbuilt-decode/src/asbuilt.py", line 101, in decode_bytes
    print(self.fieldsizes[i])
TypeError: 'NoneType' object is not subscriptable
```

Is it my fault? 🤔

**Comment by consp** [comment]
Probably not, there are some newer options not yet working correctly. Which version did you use? And can you send me the asbuilt?

**Comment by consp** [comment]
Never mind about the asbuit, I can get it anyway

**Comment by chaosben** [comment]
No problem ... i'm using the master-branch.

**Comment by consp** [comment]
Your asbuilt is for a Sync1 (or very early Sync 2) device by the looks of it. Those are not supported unfortunately. Or in case you have a sync 3 the asbuilt does not contain the data.

And by not supported I mean: I don't have the data to include it so unfortunately I can't do much about it.

It's looking for the 7D0-01 to 7D0-07 data and the ones in you file are missing data (hence sync 1 or 2 and not 3 or 4)

**Comment by chaosben** [comment]
You are right ... it is Sync 1. :-(

Thanks for your support!

**Comment by consp** [comment]
Thanks for the info anyway, I'll include a nicer error message.

Do be ware: While for Sync 2 most options did carry over to Sync 3, the Sync 1 are as far as I know quite different so save the originals before you change something.

**Comment by chaosben** [comment]
👍
